---
functional:
  - Пользователь должен иметь возможность войти в систему или зарегистрироваться
  - Пользователь должен иметь возможность просматривать свой кабинет и редактировать личные данные
  - Пользователь должен иметь возможность фильтровать товары по категориям
  - Пользователь должен иметь возможность собрать товары в корзину и просматривать её содерживое
  - Пользователь должен иметь возможность выбрать способ получения заказа (самовывоз или доставка)
  - Пользователь должен иметь возможность просматривать содержимое страницы заказа с ценой и способом оплаты
  - Пользователь должен иметь возможность выбрать тип оплаты заказа
  - Пользователь должен иметь возможность просмотра оставшегося времени приготовления и доставки заказа
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
